### PR TITLE
Support SASL/PLAIN and SASL/SCRAM mechanisms

### PR DESCRIPTION
**Pull request by dylanmei**
#### Description of the changes

Add support for additional SASL mechanisms for authenticating with Kafka brokers.
- `SASL/PLAIN`: https://kafka.apache.org/documentation/#security_sasl_plain
- `SASL/SCRAM`: https://kafka.apache.org/documentation/#security_sasl_scram

Link the issue it solves: https://github.com/newrelic/nri-kafka/issues/58

### Author

- [x] the PR should focus on a single subject. Change only relevant files to the problem you’re working on
Clean and format the code
- [ ] add unit tests for your changes and make sure all unit tests are passing
- [ ] add a risk label after carefully considering the "blast radius" of your changes
- [x] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [ ] assign at least one reviewer
- [ ] address the feedback 

### Reviewer

- [ ] review code for readability
- [ ] verify that high risk behavior changes are well tested
- [ ] check license for any new external dependency
- [ ] ask questions about anything that isn't clear and obvious
- [ ] approve the PR when you consider it's good to merge

### CODE REVIEW

**Comment by camdencheek** [comment]
Hi @dylanmei -- thanks for the PR! That was a quick turnaround. At a brief scan, this looks great. I'll do my best to provide a proper review ASAP, and get this merged in.

**Comment by camdencheek** [comment]
Hi @dylanmei  -- so sorry for the slow turnaround on this. It's been a whirlwind of a week. I looked over the PR and it just needed a tiny bit of touchup (mostly linter complaints), but I included my local changes in the merge. These changes will be released as part of v2.13.0, which I'm kicking off a release for right now

**Comment by tmancill** [comment]
@camdencheek Any update on this?

**Comment by camdencheek** [comment]
@tmancill this was released yesterday. It's available as part of v2.13.0. I'll try to get documentation updated on it soon

**Comment by Neustradamus** [comment]
@dylanmei: Thanks a lot for all about SCRAM.

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Pull request merged**
