### PR TITLE
Root cert

### PR DESCRIPTION
**Pull request by jecafarelli**
#### Description of the changes

fixing issue describe in this ticket
https://discuss.newrelic.com/t/using-ssl-authentication-with-nri-kafka-plugin-for-newrelic-infra-agent/96964/8

If the kafka cluster has SSL enforced it does not work properly. First issue is tls needs negotiation turned on when enforce, which I set in line 161 of connections.go

Even with this turned on, there is still an issue with expectations on how the server responds when ssl enforcement is turned on. The server exepects you to also verify. This is done by adding a client key and cert, and also having the public cert of the server so it can decrypt.

this can probably be done more efficiently; (IE we could probably grab the client cert and key from the keystore), but this is all new to me so not sure the best approach to make it better.

### CODE REVIEW

**Comment by camdencheek** [comment]
Hi @jecafarelli  -- thanks for the PR! I had it on my list to put a little work into SSL this week, so this is perfect timing. I'll likely pull this into my branch and include it as part of the additional work I'm doing around SSL

**Comment by jecafarelli** [comment]
@camdencheek awesome, let me know when its done and I can install it in our system to confirm it works.

Heads up after some testing it only works in bootstrap mode. Looks like TLS config is done in another part for the other mode you can run it.

**Comment by camdencheek** [comment]
@jecafarelli This was incorporated in the latest release. The args are named a little different, so be sure to note that when trying it out. For the only in bootstrap mode thing, make sure that you're setting the `preferred_listener` arg if you want to use the SSL listener specifically. Closing this since the changes were in the other one, but feel free to re-open or create another issue if that doesnt' work for you

**Comment by jecafarelli** [comment]
Awesome! I like to dig through code, you got a commit link I can take a look at @camdencheek ?

**Comment by camdencheek** [comment]
Take a look at b2b7c4

**Pull request closed without merging**
