### PR TITLE
Fixes #83 - add the broker id when creating the Broker client via Zookeeper

### LINKED ISSUE #83: Broker id is not set when using zookeeper discovery
##### Description of the problem

When upgrading to the latest version of nri-kafka, we started getting the following in our Kafka server logs:

```
[2020-05-13 19:38:43,586] INFO [Admin Manager on Broker 0]: Error processing describe configs request for resource ConfigResource(type=BROKER, name='-1') (kafka.server.AdminManager) org.apache.kafka.common.errors.InvalidRequestException: Unexpected broker id, expected 0 or empty string, but received ConfigResource(type=BROKER, name='-1').name
[2020-05-13 19:38:48,722] INFO [Admin Manager on Broker 0]: Error processing describe configs request for resource ConfigResource(type=BROKER, name='-1') (kafka.server.AdminManager) org.apache.kafka.common.errors.InvalidRequestException: Unexpected broker id, expected 0 or empty string, but received ConfigResource(type=BROKER, name='-1').name
[2020-05-13 19:38:56,164] INFO [Admin Manager on Broker 0]: Error processing describe configs request for resource ConfigResource(type=BROKER, name='-1') (kafka.server.AdminManager) org.apache.kafka.common.errors.InvalidRequestException: Unexpected broker id, expected 0 or empty string, but received ConfigResource(type=BROKER, name='-1').name
[2020-05-13 19:38:58,995] INFO [Admin Manager on Broker 0]: Error processing describe configs request for resource ConfigResource(type=BROKER, name='-1') (kafka.server.AdminManager) org.apache.kafka.common.errors.InvalidRequestException: Unexpected broker id, expected 0 or empty string, but received ConfigResource(type=BROKER, name='-1').name
[2020-05-13 19:39:03,993] INFO [Admin Manager on Broker 0]: Error processing describe configs request for resource ConfigResource(type=BROKER, name='-1') (kafka.server.AdminManager) org.apache.kafka.common.errors.InvalidRequestException: Unexpected broker id, expected 0 or empty string, but received ConfigResource(type=BROKER, name='-1').name
```

After inspecting the traffic (via tcpdump/wireshark) those requests were coming from our nri-kafka clients and the broker id was, in fact, set to -1.

When looking at the code, it does not look like the broker id is ever set to the proper id in the Broker object when using the zookeeper discovery configuration.

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

### PR DESCRIPTION
**Pull request by jeckhart**
#### Description of the changes
Fixes #83 - This adds the broker id to the broker configuration when brokers are discovered via Zookeeper.

Note: I attempted to add a unit test, but the code is structured in a way that calls samara.NewClient when constructing the broker, and it would have been a larger refactor to add the test.

### Author

- [X] the PR should focus on a single subject. Change only relevant files to the problem you’re working on
Clean and format the code
- [ ] add unit tests for your changes and make sure all unit tests are passing
- [ ] add a risk label after carefully considering the "blast radius" of your changes
- [X] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [ ] assign at least one reviewer
- [ ] address the feedback 

### Reviewer

- [ ] review code for readability
- [ ] verify that high risk behavior changes are well tested
- [ ] check license for any new external dependency
- [ ] ask questions about anything that isn't clear and obvious
- [ ] approve the PR when you consider it's good to merge

### CODE REVIEW

**Comment by jeckhart** [comment]
All tests pass and validated that this fixes the issue in our dev environment.

**Comment by camdencheek** [comment]
Hi @jeckhart -- Thanks for the PR! I'll have to do a little more detailed testing on this just because last time I looked at this issue, I seem to remember a change like this causing issues with the `bootstrap` discovery method. I'll try to resolve this in the next couple of days

**Comment by jeckhart** [comment]
> Hi @jeckhart -- Thanks for the PR! I'll have to do a little more detailed testing on this just because last time I looked at this issue, I seem to remember a change like this causing issues with the `bootstrap` discovery method. I'll try to resolve this in the next couple of days

Thanks @camdencheek . I believe that where I've added the broker ID is outside of the bootstrap flow entirely so hopefully it shouldn't impact them at all. An alternative option would be to default to an empty string (`""`) instead of a `"-1"`.

**Comment by camdencheek** [comment]
@jeckhart Sorry for the delay on this. It'll be released under version 2.13.3

**Pull request merged**
