### PR TITLE
Read the protocol map when decoding broker host strings

### LINKED ISSUE #47: nri-kafka does not interpret the protocol map
##### Description of the problem

When configuring nri-kafka to access my Kafka brokers, it was returning an error:
```bash
/var/db/newrelic-infra/newrelic-integrations/bin/nr-kafka -metrics -zookeeper_hosts '[{"host":"10.0.0.10","port":2181}]' -default_jmx_port 9010
2019/03/18 18:08:01 Connected to 10.0.0.10:2181
2019/03/18 18:08:01 Authenticated: id=1234567890, timeout=4000
2019/03/18 18:08:01 Re-submitting `0` credentials after reconnect
[ERR] Unable to get broker JMX information for broker id : host could not be found for broker
[ERR] Unable to get broker JMX information for broker id : host could not be found for broker
[ERR] Unable to get broker JMX information for broker id : host could not be found for broker
```

When digging through the error, this is caused because the plugin does not scan the protocol map returned by Zookeeper. 

For example, my Zookeeper return string for broker #0 is:
```json
{"listener_security_protocol_map":{"EXTERNAL":"SSL","INTERNAL":"PLAINTEXT","HEALTHCHECK":"PLAINTEXT"},"endpoints":["EXTERNAL://10.0.0.11:9092","INTERNAL://10.0.0.11:9093","HEALTHCHECK://10.0.0.11:9094"],"jmx_port":9010,"host":"10.0.0.1","timestamp":"1552918908978","port":9092,"version":4}
```

So when the plugin scans the endpoints, it gets skips the endpoints because they don't match `PLAINTEXT` or `SSL`. It needs to check the `listener_security_protocol_map` before scanning the endpoints.

I have a PR incoming for the fix.

##### OS

- [x] All of them

### PR DESCRIPTION
**Pull request by jeckhart**
#### Description of the changes

Fixes #47 

This checks the protocol map that Zookeeper returns for each broker to identify the protocol to use for each broker endpoint.

### Author

- [ ] add a risk label after carefully considering the "blast radius" of your changes
- [x] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [ ] assign at least one reviewer

### Reviewer

- [ ] review code for readability
- [ ] verify that high risk behavior changes are well tested
- [ ] check license for any new external dependency
- [ ] ask questions about anything that isn't clear and obvious
- [ ] approve the PR when you consider it's good to merge

### CODE REVIEW

**Comment by jeckhart** [comment]
Since I don't have write access I can't assign a label or assign a reviewer.

I believe the risk is low and I've added tests for the conditions.

**Comment by jeckhart** [comment]
Not sure why it says the build isn't passing and it doesn't give a log to review.

I formatted the code and all tests pass and `make` runs cleanly on my machine.

**Comment by ccheek21** [comment]
Hi @jeckhart -- Thanks for the PR! Sorry it took so long to get to this. My notification preferences apparently got all messed up and your PR flew under my radar. Taking a look at it now

**Comment by jeckhart** [comment]
Great, thanks @ccheek21 !

**Comment by ccheek21** [comment]
Changes look great. My guess is the reason the build is failing is that there are some go formatting stuff that it doesn't like. If you run `make docker-fmt && make docker-make`, it will format your code how the build system asks for it.

**Comment by dcrouch26** [comment]
I too am running into this issue! I debugged to the same point and found this PR

**Comment by ccheek21** [comment]
Fixed and merged in #60

**Pull request closed without merging**
